wip

diff --git a/scripts/tmux-sessionizer b/scripts/tmux-sessionizer
--- a/scripts/tmux-sessionizer
+++ b/scripts/tmux-sessionizer
@@ -3,26 +3,26 @@
 # Taken from https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/bin/tmux-sessionizer
 
 if [[ $# -eq 1 ]]; then
-    selected=$1
+	selected=$1
 else
-    # I need to clean up this folders
-    selected=$(find ~/Code/Sites ~/Code/Local ~/Code/side-projects ~/Code/codeable  ~/Code/static ~/Clients ~/Personal/ -mindepth 1 -maxdepth 1 -type d | fzf)
+	# I need to clean up this folders
+	selected=$(find ~/Local\ Sites ~/Code/Sites ~/Code/Personal ~/Code/Clients/acquira ~/Code/Clients/aureacode -mindepth 1 -maxdepth 1 -type d | fzf)
 fi
 
 if [[ -z $selected ]]; then
-    exit 0
+	exit 0
 fi
 
 selected_name=$(basename "$selected" | tr . _)
 tmux_running=$(pgrep tmux)
 
 if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
-    tmux new-session -s $selected_name -c $selected
-    exit 0
+	tmux new-session -s $selected_name -c $selected
+	exit 0
 fi
 
-if ! tmux has-session -t=$selected_name 2> /dev/null; then
-    tmux new-session -ds $selected_name -c $selected
+if ! tmux has-session -t=$selected_name 2>/dev/null; then
+	tmux new-session -ds $selected_name -c $selected
 fi
 
 tmux switch-client -t $selected_name
